### ISSUE TITLE
Update the docker image and variables

### ISSUE THREAD

**Issue by simplesisu** [wger-project/unraid-templates#3]
Just as the title says, could you please update docker container image and variables in the unraid ca apps so that it works with latest of your changes in dockerhub with image: wger/server:latest tried installing several times with different variables changes but no veil.

and this repo is FANTASTIC BTW so huge thanks.

Br,
a Simple Dude

**Comment by rolandgeider** [comment]
Hi! Glad that you like it 🤗

What exactly is failing?

**Comment by simplesisu** [comment]
here are the logs for the wger-unraid container...pulling wger/server:latest

```
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 443, in execute
    self.check()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/model_checks.py", line 36, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/wger/src/wger/exercises/models/base.py", line 146, in check
    no_translations = cls.no_translations.all().count()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 621, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/query.py", line 559, in get_count
    return obj.get_aggregation(using, ["__count"])["__count"]
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/query.py", line 544, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "exercises_exercisebase" does not exist
LINE 1: ... COUNT("exercises_exercise"."id") AS "count" FROM "exercises...
                                                             ^

INFO 2023-09-22 14:00:45,171 apps AXES: BEGIN version 6.1.0, blocking by ip_address
INFO 2023-09-22 14:00:45,679 apps AXES: BEGIN version 6.1.0, blocking by ip_address
INFO 2023-09-22 14:00:45,690 autoreload Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "exercises_exercisebase" does not exist
LINE 1: ... COUNT("exercises_exercise"."id") AS "count" FROM "exercises...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/model_checks.py", line 36, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/wger/src/wger/exercises/models/base.py", line 146, in check
    no_translations = cls.no_translations.all().count()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 621, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/query.py", line 559, in get_count
    return obj.get_aggregation(using, ["__count"])["__count"]
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/query.py", line 544, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "exercises_exercisebase" does not exist
LINE 1: ... COUNT("exercises_exercise"."id") AS "count" FROM "exercises...
                                                             ^

Using django's development server...
Performing system checks...
```

**Comment by rolandgeider** [comment]
Mhhhh, that sounds like the database wasn't initialized correctly

**Comment by simplesisu** [comment]
With CA app on unraid I get the error from above but (postgresql) initializes just fine when taking the docker-compose route (I get 403 error with docker-compose when trying to login using admin or registering new user)
